<a href="https://colab.research.google.com/github/stanimman/CS224N/blob/master/Working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import pandas as pd

In [3]:
print(torch.__version__)

1.1.0


In [0]:
m = np.array([[1,6,3],[2,4,1],[6,4,2],[2,5,4],[4,6,1]])

In [28]:
m

array([[1, 6, 3],
       [2, 4, 1],
       [6, 4, 2],
       [2, 5, 4],
       [4, 6, 1]])

In [0]:
outsideVectors = torch.from_numpy(m).float()

In [41]:
print(centerWordVec.dtype)

torch.float32


In [0]:
centerWordVec = torch.tensor([[1,1,1]]).float()

In [48]:
centerWordVec

tensor([[1., 1., 1.]])

In [0]:
import torch.nn.functional as F

In [44]:
outsideVectors.shape

torch.Size([5, 3])

In [49]:
centerWordVec.shape

torch.Size([1, 3])

In [0]:
x = torch.mm(outsideVectors,centerWordVec.t())

In [55]:
x

tensor([[10.],
        [ 7.],
        [12.],
        [11.],
        [11.]])

In [58]:
y_hat

tensor([[0.0721],
        [0.0036],
        [0.5325],
        [0.1959],
        [0.1959]])

In [0]:
y_hat = F.softmax(x,dim=0)

In [0]:
loss  = -np.log(y_hat[2])

In [24]:
import torch.nn.NLLLoss

ModuleNotFoundError: ignored