<a href="https://colab.research.google.com/github/stanimman/CS224N/blob/master/Working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import pandas as pd

In [3]:
print(torch.__version__)

1.1.0


In [0]:
m = np.array([[1,6,3],[2,4,1],[6,4,2],[2,5,4],[4,6,1]]).astype(float)

In [28]:
m

array([[1, 6, 3],
       [2, 4, 1],
       [6, 4, 2],
       [2, 5, 4],
       [4, 6, 1]])

In [0]:
outsideVectors = torch.from_numpy(m).float()

In [68]:
outsideVectors = torch.tensor(outsideVectors,requires_grad=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [41]:
print(centerWordVec.dtype)

torch.float32


In [67]:
centerWordVec = torch.tensor([[1,1,1]]).float()
centerWordVec = torch.tensor(centerWordVec,requires_grad=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [48]:
centerWordVec

tensor([[1., 1., 1.]])

In [0]:
import torch.nn.functional as F

In [44]:
outsideVectors.shape

torch.Size([5, 3])

In [49]:
centerWordVec.shape

torch.Size([1, 3])

In [0]:
x = torch.mm(outsideVectors,centerWordVec.t())

In [55]:
x

tensor([[10.],
        [ 7.],
        [12.],
        [11.],
        [11.]])

In [58]:
y_hat

tensor([[0.0721],
        [0.0036],
        [0.5325],
        [0.1959],
        [0.1959]])

In [0]:
y_hat = F.softmax(x,dim=0)

In [0]:
loss  = -torch.log(y_hat[2])

In [0]:
loss.backward()

In [74]:
print(outsideVectors.grad)

tensor([[ 0.0721,  0.0721,  0.0721],
        [ 0.0036,  0.0036,  0.0036],
        [-0.4675, -0.4675, -0.4675],
        [ 0.1959,  0.1959,  0.1959],
        [ 0.1959,  0.1959,  0.1959]])


In [75]:
print(centerWordVec.grad)

tensor([[-1.5501,  0.7319,  0.2644]])


In [0]:
def softmax(x):
    """Compute the softmax function for each row of the input x.
    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. 

    Arguments:
    x -- A D dimensional vector or N x D dimensional numpy matrix.
    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape

    if len(x.shape) > 1:
        # Matrix
        tmp = np.max(x, axis=1)
        x -= tmp.reshape((x.shape[0], 1))
        x = np.exp(x)
        tmp = np.sum(x, axis=1)
        x /= tmp.reshape((x.shape[0], 1))
    else:
        # Vector
        tmp = np.max(x)
        x -= tmp
        x = np.exp(x)
        tmp = np.sum(x)
        x /= tmp

    assert x.shape == orig_shape
    return x

In [0]:
outsideVectors_np = outsideVectors.data.numpy()
centerWordVec_np = centerWordVec.data.numpy()

In [87]:
outsideVectors_np

array([[1., 6., 3.],
       [2., 4., 1.],
       [6., 4., 2.],
       [2., 5., 4.],
       [4., 6., 1.]], dtype=float32)

In [88]:
centerWordVec_np

array([[1., 1., 1.]], dtype=float32)

In [0]:
x_np = np.matmul(outsideVectors_np,np.transpose(centerWordVec_np))

In [0]:
# Loss function

#x_np = np.matmul(outsideVectors_np,np.transpose(centerWordVec_np))
y_hat_np =  y_hat.data.numpy()
loss_np = -np.log(y_hat_np[2])

# Gradient of vc = Ut (y-yhat)
y = np.zeros(y_hat_np.shape)
y[2] = 1
Ind_grad  = y - y_hat_np
gradCenterVec = -(np.dot(np.transpose(Ind_grad),outsideVectors_np))

In [0]:
# Gradient of Outisde Matrix U =  (yhat - y)T.Vc
  v_exp = centerWordVec_np
  Ind_grad_exp = y_hat_np-y
  gradOutsideVecs = np.dot(Ind_grad_exp,v_exp)

In [103]:
gradCenterVec

array([[-1.55014145,  0.73185896,  0.2643881 ]])

In [0]:
tensor([[ 0.0721,  0.0721,  0.0721],
        [ 0.0036,  0.0036,  0.0036],
        [-0.4675, -0.4675, -0.4675],
        [ 0.1959,  0.1959,  0.1959],
        [ 0.1959,  0.1959,  0.1959]])

In [106]:
gradOutsideVecs

array([[ 0.07206995,  0.07206995,  0.07206995],
       [ 0.00358815,  0.00358815,  0.00358815],
       [-0.46747106, -0.46747106, -0.46747106],
       [ 0.19590645,  0.19590645,  0.19590645],
       [ 0.19590645,  0.19590645,  0.19590645]])

In [94]:
x_np

array([[10.],
       [ 7.],
       [12.],
       [11.],
       [11.]], dtype=float32)

In [85]:
y_hat_np

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [84]:
loss_np

array([-0.], dtype=float32)

In [83]:
gradCenterVec

array([[ -9., -21.,  -9.]])

In [24]:
import torch.nn.NLLLoss

ModuleNotFoundError: ignored